# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing yarn dependencies
      run: yarn install
    - name: Testing
      run: yarn test
    - name: Building
      run: yarn build
    - name: Deploy
      run: 
        |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        gh-pages -b public -d build --if-present
      env:
        user_name: 'krishnapaul242'
        user_email: 'me@krishnapaul.in'
        github_token: ${{ secrets.DEPLOY_KEY }}
        repository: ${{ github.repository }
